### ISSUE TITLE
Variable length wildcards with zero value not matching

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript-editor#15]
A trigger like `hello *~2` will match `hello John Doe` and `hello John` but will fail to match `hello`. Just tested.

**Comment by silentrob** [comment]
I just noticed I don't have a test that covers the zero use-case and I have no idea how this went so long without being caught.

So 

`*` - zero to infinity tokens
`*n` - exactly n tokens
`*~n` - Should be between zero and n tokens but is probably one to n tokens as per your tests.
`*(n-m)` - range wildcard. This _could_ deprecate the above two, but I would need to test it a little more.

**Comment by silentrob** [comment]
I just pushed a fix for variable length wildcards. It should work now 0 - n. I will update the editor and push the matching version so you can test it.

**Comment by silentrob** [comment]
It is in superscript@0.8.7 npm update should pull it in.
