### ISSUE TITLE
Assertion failed: (wrap->refs_ == 0), function WeakCallback

### ISSUE THREAD

**Issue by siddharthg** [silentrob/superscript-editor#28]
`Assertion failed: (wrap->refs_ == 0), function WeakCallback, file /Users/christkv/.node-gyp/1.6.1/src/node_object_wrap.h, line 103.
Abort trap: 6`

This comes as soon as I start the server. As soon as I am new to this, but there in no user on my computer called christkv, thus posting it here, anyone having similar issue?

**Comment by mariusursache** [comment]
It's a MongoDB issue. Chris KV (https://github.com/christkv/mongodb-core)
is the developer of one of the Mongo drivers.

**Comment by siddharthg** [comment]
Thanks, reinstalling the MongoDB's node_module solved the issue for me.
