### ISSUE TITLE
Editor crashes if gambit not found

### ISSUE THREAD

**Issue by ArkeologeN** [silentrob/superscript-editor#36]
An error came up similar to `cannot read property parent of undefined`and that's coming from a database record property.

Here's more:

```
/home/deploy/code/superscript-editor/node_modules/superscript/lib/topics/common.js:22
        if (reply.parent.parent) {
                        ^
TypeError: Cannot read property 'parent' of undefined

```

**Comment by wac81** [comment]
same issue ,how to fix?

**Comment by ArkeologeN** [comment]
The great solution is stop using editor! :) We're just using the exported bot module now, but I think the issue was due to existing data. Just for a safer side, try dropping your database and run the gambit again.

**Comment by silentrob** [comment]
updated the readme. please use the CLI in SuperScript.
