### ISSUE TITLE
Node.js v0.12.0 compatibility?

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript-editor#7]
In the installation manual, here: https://github.com/silentrob/superscript-editor
I read that is needed node.js 0.10.x , do you think that also the usage of node.js v0.12.0 will be all right too?

**Comment by airport-transfers** [comment]
Sorry for my mistake, the question is for https://github.com/silentrob/superscript/ and not only it editor.

**Comment by silentrob** [comment]
This should be fixed now.
