### ISSUE TITLE
MongoDB space

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript-editor#8]
How much MongoDB space is needed for a clean setup? and how much for around 1 hundred Gambits with 3 reply?

**Comment by airport-transfers** [comment]
Sorry for my mistake, the question is about https://github.com/silentrob/superscript/ and not only the editor.

**Comment by silentrob** [comment]
I have a testbot that has 1070 Gambits, 3370 Replies, 34 Topics 320 users and it is 8MB even.

Sorry I missed this issue when you first posted it.
